export const SET_SOURCE_HTML = 'SET_SOURCE_HTML'
export const SET_IS_SIMULATION = 'SET_IS_SIMULATION'
export const SET_SUBJECTS = 'SET_SUBJECTS'
export const SET_IS_EDITING = 'SET_IS_EDITING'
export const SET_SELECTED_SUBJECT_KEYS = 'SET_SELECTED_SUBJECT_KEYS'

export default {
  SET_SOURCE_HTML,
  SET_IS_SIMULATION,
  SET_SUBJECTS,
  SET_IS_EDITING,
  SET_SELECTED_SUBJECT_KEYS
}
